FROM tmigone/librespot:0.3.1-pulseaudio

RUN install_packages jq

ENV PULSE_SERVER=tcp:localhost:4317

COPY start.sh /usr/src/

COPY auto_spotify.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
